---
title: "Design of an Analog-Digital-Converter the Delta-Sigma way"

bibliography: references.bib
---

{{< include chapters/introduction/introduction.qmd >}}

{{< include chapters/theory/theory.qmd >}}

{{< include chapters/ideal_circ/ideal_circ.qmd >}}

# Design Proposals
This chapter shall highlight our attempts at realizing the desired subsystems of the $\Delta\Sigma$ modulator on transistor level, utilizing the 130 nm technology offered from the IHP's sg13g2 BiCMOS PDK for open source usage.

The following subchapters will elaborate on the separate subcircuits, briefly explain the workings of the circuits before going over the achieved simulation results. Xschem was used as the schematic capture EDA tool, while the testbench-driven simulations utilize ngspice. 

| Component                    | Device Name    | Specifications                                                   |
|:-----------------------------|:---------------|:-----------------------------------------------------------------|
| Low-voltage (LV) NMOS        | `sg13_lv_nmos` | operating voltage (nom.) $\VDD=1.5\,\text{V}$, $L_\mathrm{min}=0.13\,\mu\text{m}$, $\Vth \approx 0.5\,\text{V}$; isolated NMOS available |
| Low-voltage (LV) PMOS        | `sg13_lv_pmos` | operating voltage (nom.) $\VDD=1.5\,\text{V}$, $L_\mathrm{min}=0.13\,\mu\text{m}$, $\Vth \approx -0.47\,\text{V}$ |
| High-voltage (HV) NMOS       | `sg13_hv_nmos` | operating voltage (nom.) $\VDD=3.3\,\text{V}$, $L_\mathrm{min}=0.45\,\mu\text{m}$, $\Vth \approx 0.7\,\text{V}$; isolated NMOS available |
| High-voltage (HV) PMOS       | `sg13_hv_pmos` | operating voltage (nom.) $\VDD=3.3\,\text{V}$, $L_\mathrm{min}=0.45\,\mu\text{m}$, $\Vth \approx -0.65\,\text{V}$ |
| Silicided poly resistor      | `rsil`         | $R_\square=7\,\Omega \pm 10\%$, $\text{TC}_1=3100\,\text{ppm/K}$ |
| Poly resistor                | `rppd`         | $R_\square=260\,\Omega \pm 10\%$, $\text{TC}_1=170\,\text{ppm/K}$ |
| Poly resistor high           | `rhigh`        | $R_\square=1360\,\Omega \pm 15\%$, $\text{TC}_1=-2300\,\text{ppm/K}$ |
| MIM capacitor                | `cap_cmim`     | $C'=1.5\,\text{fF}/\mu\text{m}^2 \pm 10\%$, $\text{VC}_1=-26\text{ppm/V}$, $\text{TC}_1=3.6\text{ppm/K}$, breakdown voltage $>15\,\text{V}$ |
| MOM capacitor                | n/a            | The metal stack is well-suited for MOM capacitors due to 5 thin metal layers, but no primitive capacitor device is available at this point. |

: IHP SG13G2 devices {#tbl-sg13g2-devices}[@pretl2025]

{{< include chapters/clock_gen/clock_gen.qmd >}}

{{< include chapters/switch_cap_int_design/design.qmd >}}

{{< include chapters/design/comparator/comp.qmd >}}

{{< include chapters/decimator/decimator.qmd >}}

# Conclusion

We have come to the end of this design document. 

# References
